version: '3.8'

services:
  # 1. Database Service (Automated official image)
  database:
    image: mongo:latest
    container_name: data-entry-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 2. Backend Service
  backend:
    build: ./backend
    image: data-entry-backend:dev  # Matches your exact backend image name
    container_name: data-entry-api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://database:27017/mern-crud
    depends_on:
      - database

  # 3. Frontend Service
  frontend:
    build: ./frontend
    image: data-entry-frontend:dev         # Matches your exact frontend image name
    container_name: data-entry-frontend
    ports:
      - "5173:5173"               # Fixed to match the 5173 port from your image
    depends_on:
      - backend

volumes:
  mongo-data: